# Generated by Django 4.2.7 on 2023-11-29 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kategori', models.CharField(choices=[('projects', 'projects'), ('areas', 'areas'), ('resources', 'resources'), ('archives', 'archives')], max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('lokasi', models.CharField(blank=True, default='', max_length=100)),
                ('waktu_pengingat', models.DateTimeField(blank=True, null=True)),
                ('tenggat_waktu', models.DateTimeField(blank=True, null=True)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kategori', models.CharField(choices=[('projects', 'projects'), ('areas', 'areas'), ('resources', 'resources'), ('archives', 'archives')], max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('lokasi', models.CharField(blank=True, default='', max_length=100)),
                ('waktu_pengingat', models.DateTimeField(blank=True, null=True)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_akhir', models.DateTimeField()),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_acara', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
